# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7f7f4c96c29bbe8b42ad4947826bab2fc582e7c9ca1f2203b8749a2f2f179bf8e215654ea8ae2942b5e37c49ac960c102698f5234b30b675366293c62e17957

test:
  secret_key_base: b1a2098a5cfeca1aebf621b75cd5e299aac211db52a127f740c3e761c7499f982f425598f6f652f6f0ebcab664c696bccea1df681c5775e6c9065c9c310bdec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
